name: GitHub CI/CD Discord Notification

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: "https://discord.com/api/webhooks/1538385654591782993/_khQaf3PrN9_2Lh4oeryOj4NuVSbjgHX03IEhfecdrgiBJjCyrSn6t5ATtv5Xvs5RFtk"
          content: "🚀 **Có commit mới!**\n📌 **Commit:** ${{ github.event.head_commit.message }}\n👤 **Người commit:** ${{ github.actor }}\n📦 **Repository:** ${{ github.repository }}\n🔗 **URL:** ${{ github.event.head_commit.url }}"
