name: GitHub CI/CD Discord Notification

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "🚀 **Có commit mới!**\n📌 **Commit:** ${{ github.event.head_commit.message }}\n👤 **Người commit:** ${{ github.actor }}\n🔗 **URL:** ${{ github.event.head_commit.url }}"}' \
               https://discord.com/api/webhooks/1538385654591782993/_khQaf3PrN9_2Lh4oeryOj4NuVSbjgHX03IEhfecdrgiBJjCyrSn6t5ATtv5Xvs5RFtk